import { Company, Portfolio, BlogPost, Review } from '@/types';

export const mockCompanies: Company[] = [
  {
    id: '1',
    userId: 'u1',
    companyName: '그린가든 조경',
    businessNumber: '123-45-67890',
    representative: '김정원',
    description: '20년 경력의 정원 전문 조경회사입니다. 모던하고 세련된 정원 디자인을 추구하며, 고객의 라이프스타일에 맞는 맞춤형 정원을 만들어드립니다.',
    logo: '/images/mock/company1-logo.jpg',
    coverImage: '/images/mock/company1-cover.jpg',
    address: '서울특별시 강남구',
    phone: '02-1234-5678',
    specialties: ['정원 설계', '모던 조경', '수경시설'],
    serviceAreas: ['서울', '경기'],
    established: '2004',
    isVerified: true,
    isApproved: true,
    rating: 4.8,
    reviewCount: 127,
    projectCount: 89,
  },
  {
    id: '2',
    userId: 'u2',
    companyName: '자연과 사람들',
    businessNumber: '234-56-78901',
    representative: '박자연',
    description: '자연을 닮은 정원을 만듭니다. 한국 전통 정원과 자연주의 조경을 전문으로 하며, 생태적으로 건강한 정원을 설계합니다.',
    logo: '/images/mock/company2-logo.jpg',
    coverImage: '/images/mock/company2-cover.jpg',
    address: '경기도 용인시',
    phone: '031-2345-6789',
    specialties: ['한국 전통', '자연주의', '생태 정원'],
    serviceAreas: ['경기', '서울', '충남'],
    established: '2010',
    isVerified: true,
    isApproved: true,
    rating: 4.9,
    reviewCount: 95,
    projectCount: 67,
  },
  {
    id: '3',
    userId: 'u3',
    companyName: '모던스케이프',
    businessNumber: '345-67-89012',
    representative: '이현대',
    description: '미니멀하고 모던한 조경 디자인 전문. 옥상 정원, 베란다 가드닝, 상업시설 조경까지 도시형 조경의 모든 것을 제공합니다.',
    logo: '/images/mock/company3-logo.jpg',
    coverImage: '/images/mock/company3-cover.jpg',
    address: '서울특별시 성동구',
    phone: '02-3456-7890',
    specialties: ['옥상 조경', '미니멀', '상업시설'],
    serviceAreas: ['서울', '경기', '인천'],
    established: '2015',
    isVerified: true,
    isApproved: true,
    rating: 4.7,
    reviewCount: 64,
    projectCount: 45,
  },
  {
    id: '4',
    userId: 'u4',
    companyName: '숲속정원',
    businessNumber: '456-78-90123',
    representative: '최숲',
    description: '영국식 코티지 가든과 자연스러운 숲 정원을 전문으로 합니다. 사계절 아름다운 정원을 만들어드립니다.',
    logo: '/images/mock/company4-logo.jpg',
    coverImage: '/images/mock/company4-cover.jpg',
    address: '경기도 파주시',
    phone: '031-4567-8901',
    specialties: ['영국식 정원', '숲 정원', '계절 정원'],
    serviceAreas: ['경기', '서울'],
    established: '2012',
    isVerified: true,
    isApproved: true,
    rating: 4.6,
    reviewCount: 52,
    projectCount: 38,
  },
];

export const mockPortfolios: Portfolio[] = [
  {
    id: 'p1',
    companyId: '1',
    company: mockCompanies[0],
    title: '판교 단독주택 모던 정원 프로젝트',
    content: '',
    excerpt: '깔끔한 라인과 미니멀한 식재 디자인으로 완성한 판교 단독주택 정원입니다.',
    coverImage: '/images/mock/portfolio1.jpg',
    beforeImages: ['/images/mock/before1.jpg'],
    afterImages: ['/images/mock/after1.jpg'],
    processImages: [],
    projectType: 'GARDEN',
    style: 'MODERN',
    area: 150,
    duration: '4주',
    location: '경기도 성남시 판교',
    budget: '3,000만원 ~ 5,000만원',
    plants: ['단풍나무', '라벤더', '그라스류', '호스타'],
    materials: ['화강석', '방부목 데크', 'LED 조명'],
    isPublished: true,
    views: 1520,
    likes: 89,
    createdAt: '2024-02-15',
  },
  {
    id: 'p2',
    companyId: '2',
    company: mockCompanies[1],
    title: '용인 전원주택 한국식 자연정원',
    content: '',
    excerpt: '한국 전통 정원의 멋과 자연주의 식재를 결합한 전원주택 정원 프로젝트입니다.',
    coverImage: '/images/mock/portfolio2.jpg',
    beforeImages: ['/images/mock/before2.jpg'],
    afterImages: ['/images/mock/after2.jpg'],
    processImages: [],
    projectType: 'GARDEN',
    style: 'TRADITIONAL',
    area: 300,
    duration: '6주',
    location: '경기도 용인시',
    budget: '5,000만원 ~ 1억원',
    plants: ['소나무', '매화', '대나무', '이끼'],
    materials: ['자연석', '황토', '기와'],
    isPublished: true,
    views: 2340,
    likes: 156,
    createdAt: '2024-01-20',
  },
  {
    id: 'p3',
    companyId: '3',
    company: mockCompanies[2],
    title: '성수동 카페 옥상정원 조성',
    content: '',
    excerpt: '도심 속 작은 숲, 성수동 카페 옥상을 초록으로 가득 채운 프로젝트입니다.',
    coverImage: '/images/mock/portfolio3.jpg',
    beforeImages: ['/images/mock/before3.jpg'],
    afterImages: ['/images/mock/after3.jpg'],
    processImages: [],
    projectType: 'ROOFTOP',
    style: 'MODERN',
    area: 80,
    duration: '3주',
    location: '서울특별시 성동구',
    budget: '1,000만원 ~ 3,000만원',
    plants: ['올리브나무', '로즈마리', '다육식물', '아이비'],
    materials: ['인조목 데크', '화분', '자동관수'],
    isPublished: true,
    views: 3100,
    likes: 210,
    createdAt: '2024-03-01',
  },
  {
    id: 'p4',
    companyId: '4',
    company: mockCompanies[3],
    title: '파주 영국식 코티지 가든',
    content: '',
    excerpt: '사계절 꽃이 피는 영국식 코티지 가든을 파주 전원주택에 구현했습니다.',
    coverImage: '/images/mock/portfolio4.jpg',
    beforeImages: ['/images/mock/before4.jpg'],
    afterImages: ['/images/mock/after4.jpg'],
    processImages: [],
    projectType: 'GARDEN',
    style: 'ENGLISH',
    area: 200,
    duration: '5주',
    location: '경기도 파주시',
    budget: '3,000만원 ~ 5,000만원',
    plants: ['장미', '라벤더', '수국', '클레마티스', '피오니'],
    materials: ['고벽돌', '자갈', '아치', '벤치'],
    isPublished: true,
    views: 1890,
    likes: 134,
    createdAt: '2024-02-28',
  },
  {
    id: 'p5',
    companyId: '1',
    company: mockCompanies[0],
    title: '강남 타운하우스 미니멀 정원',
    content: '',
    excerpt: '제한된 공간을 최대한 활용한 도시형 미니멀 정원 프로젝트입니다.',
    coverImage: '/images/mock/portfolio5.jpg',
    beforeImages: ['/images/mock/before5.jpg'],
    afterImages: ['/images/mock/after5.jpg'],
    processImages: [],
    projectType: 'GARDEN',
    style: 'MINIMAL',
    area: 60,
    duration: '2주',
    location: '서울특별시 강남구',
    budget: '1,000만원 ~ 3,000만원',
    plants: ['대나무', '흑송', '그라스류'],
    materials: ['노출 콘크리트', '코르텐 스틸', 'LED'],
    isPublished: true,
    views: 980,
    likes: 67,
    createdAt: '2024-03-05',
  },
  {
    id: 'p6',
    companyId: '2',
    company: mockCompanies[1],
    title: '제주 펜션 자연주의 정원',
    content: '',
    excerpt: '제주의 자연과 어우러지는 자연주의 정원을 펜션에 조성했습니다.',
    coverImage: '/images/mock/portfolio6.jpg',
    beforeImages: ['/images/mock/before6.jpg'],
    afterImages: ['/images/mock/after6.jpg'],
    processImages: [],
    projectType: 'COMMERCIAL',
    style: 'NATURAL',
    area: 500,
    duration: '8주',
    location: '제주특별자치도',
    budget: '5,000만원 ~ 1억원',
    plants: ['야자수', '동백', '수선화', '제주 자생식물'],
    materials: ['현무암', '제주석', '자연목'],
    isPublished: true,
    views: 4200,
    likes: 287,
    createdAt: '2024-01-10',
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'b1',
    authorId: 'admin',
    title: '2024 조경 트렌드: 자연과 기술의 만남',
    slug: '2024-landscaping-trends',
    content: '',
    excerpt: '올해 주목해야 할 조경 트렌드를 소개합니다. 스마트 가든, 자생식물 활용, 지속가능한 조경까지.',
    coverImage: '/images/mock/blog1.jpg',
    category: 'TREND',
    tags: ['트렌드', '스마트가든', '2024'],
    isPublished: true,
    publishedAt: '2024-03-01',
    views: 3450,
    createdAt: '2024-03-01',
  },
  {
    id: 'b2',
    authorId: 'admin',
    title: '초보자를 위한 정원 식물 가이드: 키우기 쉬운 식물 TOP 10',
    slug: 'beginner-plant-guide-top10',
    content: '',
    excerpt: '정원 가꾸기를 처음 시작하시나요? 초보자도 쉽게 키울 수 있는 정원 식물 10가지를 추천합니다.',
    coverImage: '/images/mock/blog2.jpg',
    category: 'PLANT_GUIDE',
    tags: ['초보자', '식물추천', '가이드'],
    isPublished: true,
    publishedAt: '2024-02-25',
    views: 5670,
    createdAt: '2024-02-25',
  },
  {
    id: 'b3',
    authorId: 'admin',
    title: '정원 조경, 얼마나 들까? 비용 총정리',
    slug: 'garden-landscaping-cost-guide',
    content: '',
    excerpt: '정원 조경 비용이 궁금하신가요? 면적별, 스타일별 예상 비용을 상세하게 안내해드립니다.',
    coverImage: '/images/mock/blog3.jpg',
    category: 'COST_GUIDE',
    tags: ['비용', '견적', '가이드'],
    isPublished: true,
    publishedAt: '2024-02-20',
    views: 8920,
    createdAt: '2024-02-20',
  },
  {
    id: 'b4',
    authorId: 'admin',
    title: '봄맞이 정원 관리 체크리스트',
    slug: 'spring-garden-maintenance-checklist',
    content: '',
    excerpt: '봄이 오기 전 정원을 준비하세요! 전정, 시비, 식재까지 봄맞이 정원 관리 완벽 가이드.',
    coverImage: '/images/mock/blog4.jpg',
    category: 'SEASONAL',
    tags: ['봄', '관리', '체크리스트'],
    isPublished: true,
    publishedAt: '2024-02-15',
    views: 4560,
    createdAt: '2024-02-15',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    projectId: 'proj1',
    customerId: 'c1',
    customer: { id: 'c1', email: 'kim@example.com', name: '김**', role: 'CUSTOMER', createdAt: '2024-01-01' },
    companyId: '1',
    rating: 5,
    designRating: 5,
    qualityRating: 5,
    communicationRating: 5,
    scheduleRating: 4,
    valueRating: 5,
    content: '정말 만족스러운 시공이었습니다. 디자인부터 완공까지 꼼꼼하게 진행해주셨고, 특히 식재 선택에 대한 전문적인 조언이 큰 도움이 되었습니다.',
    images: ['/images/mock/review1.jpg'],
    createdAt: '2024-03-01',
  },
  {
    id: 'r2',
    projectId: 'proj2',
    customerId: 'c2',
    customer: { id: 'c2', email: 'park@example.com', name: '박**', role: 'CUSTOMER', createdAt: '2024-01-15' },
    companyId: '2',
    rating: 5,
    designRating: 5,
    qualityRating: 5,
    communicationRating: 4,
    scheduleRating: 5,
    valueRating: 4,
    content: '한국 전통 정원의 멋을 현대적으로 잘 해석해주셨습니다. 이웃들도 정원을 보고 감탄할 정도입니다.',
    images: ['/images/mock/review2.jpg'],
    createdAt: '2024-02-20',
  },
  {
    id: 'r3',
    projectId: 'proj3',
    customerId: 'c3',
    customer: { id: 'c3', email: 'lee@example.com', name: '이**', role: 'CUSTOMER', createdAt: '2024-02-01' },
    companyId: '1',
    rating: 4,
    designRating: 5,
    qualityRating: 4,
    communicationRating: 4,
    scheduleRating: 3,
    valueRating: 4,
    content: '디자인은 매우 만족스러웠지만 일정이 조금 늦어진 점이 아쉬웠습니다. 그래도 결과물은 기대 이상이에요!',
    images: [],
    createdAt: '2024-02-10',
  },
];
